In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
#텍스트 토큰화

from tensorflow.keras.preprocessing.text import text_to_word_sequence

#전처리할 텍스트

text = '노력이 있어야 무엇이든 해낼 수 있다'

#토큰화
result = text_to_word_sequence(text)

print('원문 : ', text)
print('토큰화: ',result)

원문 :  노력이 있어야 무엇이든 해낼 수 있다
토큰화:  ['노력이', '있어야', '무엇이든', '해낼', '수', '있다']


In [9]:
#토큰화 (빈도출력)

from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

#함수 지정
token = Tokenizer()

#토큰화 함수 문장 적용
token.fit_on_texts(docs)

print('단어카운트 : \n', token.word_counts)
print()
print('문장카운트 : \n', token.document_count)
print()
print('각 단어가 몇개의 문장에 포함되었는가 : \n', token.word_docs)
print()
print('각 단어에 매겨진 인덱스 값: \n', token.word_index)




단어카운트 : 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장카운트 : 
 3

각 단어가 몇개의 문장에 포함되었는가 : 
 defaultdict(<class 'int'>, {'각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '텍스트의': 2, '먼저': 1, '인식됩니다': 1, '딥러닝에서': 2, '토큰화해야': 1, '단어로': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '결과는': 1, '사용할': 1})

각 단어에 매겨진 인덱스 값: 
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [10]:
#단어의 원-핫 인코딩

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [13]:
x = token.texts_to_sequences([text])
x

[[1, 2, 3, 4, 5, 6]]

In [14]:
from tensorflow.keras.utils import to_categorical

#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [31]:
#단어 임베딩
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from numpy import array

model = Sequential()

#단어수는 16개, 출력되는 벡터크기는 4로 하겠다.
# Embedding(16,4, input_length=2) >> 단어수는 16개지만 매번 두번만 넣겠다.
model.add(Embedding(16,4))


In [32]:
#텍스트 긍부정 예측하기

docs = ['너무 재밌네요', '최고예요!', '참 잘 만든 영화예요', '추정하고 싶은 영화입니다',
'한 번 더 보고싶네요!', '글쎄요!', '별로예요', '생각보다 지루하네요.', '연기가 어색해요!', '재미없어요']

# 긍정리뷰 1, 부정리뷰 0
classes = array([1,1,1,1,1,0,0,0,0,0])


In [33]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추정하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [34]:
x = token.texts_to_sequences(docs)

#한 문장마다 토큰의 개수가 다름 (딥러닝 모델을 입력하려면 데이터의 길이가 동일해야한다 )
print('리뷰 텍스트, 토큰화결과: \n', x)

리뷰 텍스트, 토큰화결과: 
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [36]:
#패딩(padding)작업 (길이를 맞추기 위해) pad_sequences()
# 서로 다른 길이의 데이터를 4로 맞춤

padded_x = pad_sequences(x, 4)
print('패딩 결과 : \n', padded_x)



패딩 결과 : 
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [37]:
#임베딩에 입력될 단어의 수를 지정
word_size = len(token.word_index) + 1
print('단어수 : ', word_size)

단어수 :  22


In [38]:
#단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 4, 8)              176       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 209 (836.00 Byte)
Trainable params: 209 (836.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print('Accuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 0.6950 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6925 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6899 - accuracy: 0.7000
Epoch 4/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6874 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6849 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6824 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6799 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6774 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6749 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6724 - accuracy: 0.8000
Epoch 11/20
1/1 [===============